### ISSUE TITLE
Undefined class 'ETHEREUM_STATUS_DISABLED'

### ISSUE THREAD

**Issue by ahmedcharef** [Coinsence/humhub-modules-ethereum#17]
Hi guys,

I have cloned the repository and copied the module to humhub modules directly. (/protected/humhub/modules)

Also I have enabled the module from Administration menu and everything works fine.

But, when I have integrated the module into a space, I got an error "Undefined class constant 'ETHEREUM_STATUS_DISABLED'"
![image](https://user-images.githubusercontent.com/12074429/87425670-fc4f9000-c5d5-11ea-9ce7-d8fc76f0cdf3.png)

Thanks in advance.

**Comment by gdalyy** [comment]
Hello, did you pull the last updates from https://github.com/Coinsence/humhub ?

**Comment by ahmedcharef** [comment]
> Hello, did you pull the last updates from https://github.com/Coinsence/humhub ?

Yes, I have used the last update, the same error.

**Comment by gdalyy** [comment]
Can you ensure that the class constant `ETHEREUM_STATUS_DISABLED` exists in **path/to/root/protected/humhub/modules/space/models/Space.php** ?

**Comment by ahmedcharef** [comment]
the class constant doesn't exists in the path "path/to/root/protected/humhub/modules/space/models/Space.php"

**Comment by gdalyy** [comment]
as you can see [here](https://github.com/Coinsence/humhub/blob/master/protected/humhub/modules/space/models/Space.php), the class constant exists.

Maybe you've pulled the master branch from the main humhub repository and not from coinsence humhub repository

**Comment by KarimChabrak** [comment]
@ahmedcharef , I hope you are doing well.   Can we close this issue?

**Comment by ahmedcharef** [comment]
> @ahmedcharef , I hope you are doing well. Can we close this issue?

Hi, good, hope you are doing well too.

Yes, I will close it now, good job guys !
